name: Deploy beta-eye-react

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '18'
      # 3. 安装依赖
      - name: Install dependencies
        run: npm i -g yarn && yarn
      # 4. 构建项目
      - name: Build the project
        run: npm run build
      # 5. 使用 SSH 通过 rsync 部署文件
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "eye/"  # 打包后输出的目录，比如 dist 或 build
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_PATH }}